#!/bin/bash

# 🚀 QRPIPAY DEPLOYMENT SCRIPT - RENDER.COM
# Deployment Checklist & Quick Reference

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                                                               ║"
echo "║  🚀 QRPIPAY DEPLOYMENT - RENDER.COM 🚀                      ║"
echo "║                                                               ║"
echo "║  Même compte GitHub/Render? ✅ PARFAIT!                     ║"
echo "║                                                               ║"
echo "╚═══════════════════════════════════════════════════════════════╝"

echo ""
echo "📋 ÉTAPES DE DÉPLOIEMENT"
echo "════════════════════════════════════════════════════════════════"
echo ""

# STEP 1
echo "STEP 1️⃣  GÉNÉRER JWT_SECRET"
echo "─────────────────────────────────────────────────────────────────"
echo "Exécutez cette commande et copiez le résultat:"
echo ""
echo "node -e \"console.log(require('crypto').randomBytes(32).toString('hex'))\""
echo ""
echo "📋 Sauvegardez ce résultat dans un bloc-notes sûr!"
echo ""

# STEP 2
echo ""
echo "STEP 2️⃣  ALLER SUR RENDER.COM"
echo "─────────────────────────────────────────────────────────────────"
echo "1. Allez à: https://dashboard.render.com"
echo "2. Connectez-vous avec votre compte GitHub"
echo "   (Vous êtes connecté? ✅ Parfait!)"
echo ""

# STEP 3
echo ""
echo "STEP 3️⃣  CRÉER BASE DE DONNÉES POSTGRESQL"
echo "─────────────────────────────────────────────────────────────────"
echo "Actions:"
echo "  1. Cliquez: New + → PostgreSQL"
echo "  2. Remplissez le formulaire:"
echo "     • Name: qrpipay-db"
echo "     • Database: qrpipay"
echo "     • User: qrpipay"
echo "     • Region: Oregon (ou votre région)"
echo "     • Plan: Free"
echo "  3. Cliquez: Create Database"
echo "  4. Attendez 1-2 minutes"
echo "  5. IMPORTANT: Copiez l'URL Internal Database"
echo "     (Format: postgresql://user:pass@host:5432/qrpipay)"
echo ""
echo "📋 SAUVEGARDEZ CETTE URL!"
echo ""

# STEP 4
echo ""
echo "STEP 4️⃣  DÉPLOYER BACKEND SERVICE"
echo "─────────────────────────────────────────────────────────────────"
echo "Actions:"
echo "  1. Cliquez: New + → Web Service"
echo "  2. Sélectionnez votre repo GitHub: qrpipay"
echo "  3. Cliquez: Connect"
echo "  4. Configurez:"
echo "     • Name: qrpipay-backend"
echo "     • Environment: Node"
echo "     • Node Version: 18"
echo "     • Root Directory: backend"
echo "     • Build Command: npm install && npm run build"
echo "     • Start Command: npm start"
echo "     • Plan: Free"
echo "     • Auto-Deploy: Yes (checked)"
echo ""
echo "  5. AJOUTER VARIABLES D'ENVIRONNEMENT:"
echo ""
echo "     NodeJS_ENV           = production"
echo "     PORT                 = 3001"
echo "     DATABASE_URL         = (URL from Step 3)"
echo "     FRONTEND_URL         = https://qrpipay.onrender.com"
echo "     JWT_SECRET           = (from Step 1)"
echo "     LOG_LEVEL            = info"
echo "     PI_API_KEY           = (optional - your Pi key)"
echo "     PI_WALLET_ADDRESS    = (optional - your Pi wallet)"
echo ""
echo "  6. Cliquez: Create Web Service"
echo "  7. Attendez le déploiement (2-5 minutes)"
echo "  8. Quand il dit 'Live' en haut à droite ✅ = Backend prêt!"
echo ""

# STEP 5
echo ""
echo "STEP 5️⃣  DÉPLOYER FRONTEND SITE"
echo "─────────────────────────────────────────────────────────────────"
echo "Actions:"
echo "  1. Cliquez: New + → Static Site"
echo "  2. Sélectionnez votre repo GitHub: qrpipay"
echo "  3. Cliquez: Connect"
echo "  4. Configurez:"
echo "     • Name: qrpipay-frontend"
echo "     • Root Directory: frontend"
echo "     • Build Command: npm install && npm run build"
echo "     • Publish Directory: dist"
echo "     • Plan: Free"
echo "     • Auto-Deploy: Yes"
echo ""
echo "  5. AJOUTER VARIABLES D'ENVIRONNEMENT:"
echo ""
echo "     VITE_API_URL      = https://qrpipay-backend.onrender.com/api"
echo "     VITE_PI_APP_ID    = (optional)"
echo ""
echo "  6. Cliquez: Create Static Site"
echo "  7. Attendez (1-2 minutes)"
echo "  8. Quand 'Live' ✅ = Frontend prêt!"
echo ""

# STEP 6
echo ""
echo "STEP 6️⃣  EXÉCUTER MIGRATIONS DATABASE"
echo "─────────────────────────────────────────────────────────────────"
echo "Actions:"
echo "  1. Allez à: Dashboard → qrpipay-backend"
echo "  2. Cliquez: Shell tab"
echo "  3. Exécutez ces commandes:"
echo ""
echo "     cd database"
echo "     npm install"
echo "     npm run migrate"
echo ""
echo "  4. Attendez completion"
echo "  5. Vous devriez voir: 'Prisma migration applied' ✓"
echo ""

# STEP 7
echo ""
echo "STEP 7️⃣  TESTER ET VÉRIFIER"
echo "─────────────────────────────────────────────────────────────────"
echo "Backend Health Check:"
echo "  curl https://qrpipay-backend.onrender.com/health"
echo "  Devrait retourner: {\"status\":\"ok\",\"timestamp\":\"...\"}"
echo ""
echo "Frontend Check:"
echo "  Visitez: https://qrpipay-frontend.onrender.com"
echo "  Vérifiez:"
echo "    ✅ Page charge sans erreurs"
echo "    ✅ Login page visible"
echo "    ✅ Thème couleurs (purple/orange)"
echo "    ✅ Responsive sur mobile"
echo "    ✅ Pas d'erreurs console (F12)"
echo ""

echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "✅ RÉSUMÉ TIMELINE"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "T+0 min    → Générer JWT_SECRET (2 min)"
echo "T+2 min    → Ouvrir Render dashboard (1 min)"
echo "T+3 min    → Créer database (5 min)"
echo "T+8 min    → Déployer backend (5 min)"
echo "T+13 min   → Déployer frontend (3 min)"
echo "T+16 min   → Migrations (3 min)"
echo "T+19 min   → Tester & vérifier (5 min)"
echo "T+24 min   → 🎉 LIVE! 🎉"
echo ""

echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "📌 IMPORTANT REMINDERS"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "⚠️  JWT_SECRET:"
echo "    • Générez avec la commande ci-dessus"
echo "    • NE JAMAIS le mettre dans GitHub"
echo "    • Sauvegardez-le quelque part de sûr"
echo ""
echo "⚠️  DATABASE_URL:"
echo "    • Utilisez l'URL INTERNE (pas External)"
echo "    • Copier exactement depuis Render"
echo "    • Nécessaire pour backend"
echo ""
echo "⚠️  FRONTEND_URL:"
echo "    • Doit matcher votre frontend Render URL"
echo "    • Utilisé pour CORS configuration"
echo ""
echo "⚠️  VITE_API_URL:"
echo "    • Doit pointer vers votre backend Render URL"
echo "    • Format: https://qrpipay-backend.onrender.com/api"
echo ""

echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "🎯 URLS FINALES (après déploiement)"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "Frontend:  https://qrpipay-frontend.onrender.com"
echo "Backend:   https://qrpipay-backend.onrender.com"
echo "API:       https://qrpipay-backend.onrender.com/api"
echo ""

echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "❓ PROBLÈMES?"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "Frontend blank page?         → Check F12 Console"
echo "Backend build fails?         → Check Render Logs"
echo "Database connection error?   → Verify DATABASE_URL"
echo "CORS errors?                 → Check FRONTEND_URL"
echo ""
echo "Pour plus d'aide, voir:"
echo "  • DEPLOYMENT_GUIDE.md (Detailed)"
echo "  • RENDER_GUIDE.md (Technical Reference)"
echo "  • TROUBLESHOOTING section"
echo ""

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                                                               ║"
echo "║  👉 COMMENCEZ PAR L'ÉTAPE 1: GÉNÉRER JWT_SECRET             ║"
echo "║                                                               ║"
echo "║  Ensuite suivez les 7 étapes dans l'ordre                   ║"
echo "║                                                               ║"
echo "║  VOUS AVEZ CECI! LET'S GO! 🚀                               ║"
echo "║                                                               ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
