services:
  - type: pserv
    name: qrpipay-db
    plan: free
    region: frankfurt

  - type: web
    name: qrpipay-backend
    env: node
    plan: free
    region: frankfurt
    repo: https://github.com/PORTRAITART1/QRPiPay.git
    branch: master
    rootDir: backend
    buildCommand: npm install --legacy-peer-deps
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: qrpipay-frontend
    env: node
    plan: free
    region: frankfurt
    repo: https://github.com/PORTRAITART1/QRPiPay.git
    branch: master
    rootDir: frontend
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npx serve -s dist -l 3000
